# Generated by Django 5.2.15 on 2026-06-26 17:28

import django.db.models.deletion
import django.utils.timezone
import matching.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('email_body', models.TextField()),
                ('cover_letter', models.TextField(blank=True)),
                ('cv_letter', models.TextField(blank=True)),
                ('generated_resume_note', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('willing_remote', models.BooleanField(default=True)),
                ('work_authorization', models.CharField(blank=True, max_length=160)),
                ('years_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('salary_expectation', models.PositiveIntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills.')),
                ('education', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('relevant_experience', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('template_type', models.CharField(choices=[('email', 'Email body'), ('cover_letter', 'Cover letter'), ('cv_letter', 'CV letter'), ('resume_note', 'Resume note')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['template_type', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoringWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('attachment_snapshot', models.JSONField(default=list)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='matching.applicationdraft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('cv', 'CV'), ('cover_letter', 'Cover letter'), ('other', 'Other')], default='resume', max_length=30)),
                ('file', models.FileField(upload_to='candidate_documents/', validators=[matching.models.validate_upload_file])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='matching.candidate')),
            ],
            options={
                'ordering': ['candidate', 'document_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('remote_allowed', models.BooleanField(default=False)),
                ('min_years_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated must-have skills.')),
                ('preferred_skills', models.TextField(blank=True, help_text='Comma-separated nice-to-have skills.')),
                ('work_authorization', models.CharField(blank=True, max_length=160)),
                ('education_requirements', models.TextField(blank=True)),
                ('certification_requirements', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('must_have_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed')], default='open', max_length=20)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='matching.employer')),
            ],
            options={
                'ordering': ['employer__name', 'title'],
                'unique_together': {('employer', 'title')},
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('breakdown', models.JSONField(default=dict)),
                ('reasons', models.JSONField(default=list)),
                ('must_have_failures', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='unreviewed', max_length=20)),
                ('scored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='matching.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='matching.job')),
            ],
            options={
                'ordering': ['-total_score', 'candidate__last_name'],
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.AddField(
            model_name='applicationdraft',
            name='match_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_drafts', to='matching.matchscore'),
        ),
    ]
