# Generated by Django 5.2.15 on 2026-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='years_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_years_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
