# Generated by Django 5.2.15 on 2026-06-26 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_candidate_years_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.CharField(blank=True, max_length=220)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('details', models.TextField(blank=True)),
                ('source_label', models.CharField(blank=True, max_length=220)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_records', to='matching.candidate')),
            ],
            options={
                'ordering': ['candidate', 'skill', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_answers', models.JSONField(default=dict)),
                ('gender', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.CharField(blank=True, max_length=80)),
                ('aims_number', models.CharField(blank=True, max_length=120)),
                ('nationality', models.CharField(blank=True, max_length=160)),
                ('arrival_year', models.CharField(blank=True, max_length=20)),
                ('majlis', models.CharField(blank=True, max_length=160)),
                ('unhcr_registration', models.TextField(blank=True)),
                ('marital_status', models.CharField(blank=True, max_length=120)),
                ('education_level', models.CharField(blank=True, max_length=180)),
                ('field_of_study', models.CharField(blank=True, max_length=220)),
                ('institution', models.CharField(blank=True, max_length=220)),
                ('education_year', models.CharField(blank=True, max_length=40)),
                ('education_country', models.CharField(blank=True, max_length=160)),
                ('education_verified', models.CharField(blank=True, max_length=120)),
                ('english_speaking', models.CharField(blank=True, max_length=120)),
                ('english_reading_writing', models.CharField(blank=True, max_length=120)),
                ('english_test', models.CharField(blank=True, max_length=180)),
                ('english_score', models.CharField(blank=True, max_length=120)),
                ('basic_computer_skills', models.CharField(blank=True, max_length=120)),
                ('computer_skill_level', models.CharField(blank=True, max_length=120)),
                ('willing_to_migrate', models.CharField(blank=True, max_length=120)),
                ('migration_countries', models.TextField(blank=True)),
                ('migration_reason', models.TextField(blank=True)),
                ('health_conditions', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('valid_passport', models.CharField(blank=True, max_length=120)),
                ('passport_expiry', models.CharField(blank=True, max_length=80)),
                ('can_find_own_employer', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=220)),
                ('consent_truthful', models.CharField(blank=True, max_length=80)),
                ('consent_database', models.CharField(blank=True, max_length=80)),
                ('consent_share', models.CharField(blank=True, max_length=80)),
                ('consent_contact', models.CharField(blank=True, max_length=80)),
                ('consent_more_documents', models.CharField(blank=True, max_length=80)),
                ('consent_data_storage', models.CharField(blank=True, max_length=80)),
                ('photo_document_upload', models.TextField(blank=True)),
                ('resume_upload', models.TextField(blank=True)),
                ('education_upload', models.TextField(blank=True)),
                ('certification_upload', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='matching.candidate')),
            ],
            options={
                'ordering': ['candidate__last_name', 'candidate__first_name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('source_label', models.CharField(blank=True, max_length=220)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_records', to='matching.candidate')),
            ],
            options={
                'ordering': ['candidate', 'name'],
            },
        ),
    ]
